### PR TITLE
added dark theme toggler

### PR DESCRIPTION
**Pull request by clary09**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by clary09** [comment]
I have added a toggle to swap the website to a dark theme. There is also be an auto option to match the system theme too.
Screenshot (851)
Screenshot (852)
Screenshot (853)

**Comment by Riy-a** [comment]
LGTM!

**Comment by clary09** [comment]
> LGTM!
thanks

**Comment by varsharathore16** [comment]
@clary09 Please resolve these conflicts so I can merge them!

**Comment by clary09** [comment]
> @clary09 Please resolve these conflicts so I can merge them!

done!

**Comment by RakeshPotnuru** [comment]
Just a suggestion for improvement.
How about adding a transparent background to icons?

image

image

**Comment by clary09** [comment]
> Just a suggestion for improvement. How about adding a transparent background to icons?
> 
> image
> 
> image

done! Review it once

**Review by RakeshPotnuru — APPROVED** [review]
Instead of explicitly setting a color, you can just add `background: transparent`. But it's fine.

**Review by Riy-a — APPROVED** [review]

**Comment by karnikkanojia** [comment]
@clary09 can you also make the icons white? I believe they are images so you can just use this helper class.

```css
.img-icons {
    filter: invert(1);
}
```

**Review by karnikkanojia — APPROVED** [review]

**Comment by clary09** [comment]
@varsharathore16 All the conflicts resolved !

**Pull request merged**
